### ISSUE TITLE
Last weeks I often get negative number

### ISSUE THREAD

**Issue by rhoddan** [nordicopen/easee_hass#201]
### The problem

Last weeks I often get a negative number

![Screenshot 2022-08-04 at 19 03 18](https://user-images.githubusercontent.com/33499995/182909328-1c819e3a-aefb-4b8a-963f-26924cbd2950.png)

### Version of Easee integration having the issue?

v0.9.44  

### Version of Home Assistant Core having the issue?

2022.8.0

**Comment by olalid** [comment]
So, I am guessing a lot here since you provided very little information, but you are seeing some negative values on your energy consumption graphs, is that correct?
And you are using some entity/entities provided by the easee integration as input to the energy graph?
Equalizer entity?
Can you tell us how you have configured the energy panel?

**Comment by rhoddan** [comment]
Yes, since some weeks back I get some negative numbers on my energy consumption graphs. I can fix it via development - statistics - fix function but I don't know why it happen.
I'm using sensor.easee_equalizer_home_xxxx_import_energy unity in the energy config.

The energy panel is configured as below
![Screenshot 2022-08-05 at 11 41 30](https://user-images.githubusercontent.com/33499995/183050590-39405b18-f61e-4b72-97ab-222d113e7a1c.png)

**Comment by olalid** [comment]
If/when it happens again, it would be valuable to see how that sensor has behaved during the hours where the anomaly occurred.

**Comment by olalid** [comment]
Closing due to no further activity.
