### ISSUE TITLE
Sensor usage 1 hour late

### ISSUE THREAD

**Issue by jakobschou** [nordicopen/easee_hass#387]
### The problem

Hi,

I have the Easee integration on my Home Assistant instance, and use it to record the power usage of the charger.
In the HA Energy Dashboard I am recording the usage of sensor.easee_lifetime_energy as a separate source.

Comparing the data recorded from the easee sensor with the actual energy usage (which is monitored with a slimmelezer, so actual usage), the easee sensor is always 1 hour late.

How can this be? Is it due to timezone differences? In Denmark we have GMT +1 and winter offset +1 hour.
Can you reconfigure the timezone which is used in easee integration, as this might be the problem?

### Version of Easee integration having the issue?

v0.9.56

### Version of Home Assistant Core having the issue?

2024.1.6

**Comment by olalid** [comment]
I am not 100% sure what it is you are comparing here, but if it is the energy dashboard (which uses the energy sensor as input) versus a power meter logged over time, this will be the case because of how HA works, and there is not really anything we can do about it.

I.e. the energy dashboard uses the energy meter as the input. Which updates only when the electric company's meter sends out updates. Which in many cases is only once per hour.
The power meter updates typically every 15 seconds, so it is much more fine-grained.

The way HA works is that it records data when it receives it. I.e. you can not provide a timestamp to pre or post-date when data is recorded. It is recorded when it is received, period, there is no interface to do anything else.

Since the output from the electric meter is usually sent out right on the hour mark it will be received some time after the hour mark by HA. And HA will record the difference in energy since last update as being part of the coming hour, not the past hour.

We can not solve this here, it needs to be addressed by core HA developers.

**Comment by jakobschou** [comment]
Hi, thanks for the answer.

The power monitor (slimmelezer) updates the usage every 10 seconds, and therfore I can see the actual usage of the charger exactly - eg. 8,8 kWh from 00:00-01:00, but the easee meter shows this usage from 01:00-02:00. So the data is skewed one hour late.

See my energy dashboard
[image](https://github.com/nordicopen/easee_hass/assets/79198927/752b2b77-cb8f-4a64-aa68-3a3a2f95a620)

**Comment by olalid** [comment]
Yes, but power and energy are different sensors. It is the energy sensor (kWh) that is the input to HA energy dashboard, not the power sensor (kW).
The picture you attached tells me nothing about how often your energy sensor updates.

**Comment by jakobschou** [comment]
More detailed view
![image](https://github.com/nordicopen/easee_hass/assets/79198927/81e04eea-495e-4e48-a6e7-329e1d8defe4)

**Comment by olalid** [comment]
There is no more useful information in that picture.
It is the sensor that is used for input to the HA dashboard we should be looking at to see how it behaves.
Something like sensor.xxxx_import_energy typically. If that sensor updates once per hour, that is your problem, and it can not be fixed.

**Comment by jakobschou** [comment]
It is both kWh sensors...

![image](https://github.com/nordicopen/easee_hass/assets/79198927/e4b867c6-c1c3-4a81-a164-7f8340e39027)

The total energy sensor is updated every 10 sec

![image](https://github.com/nordicopen/easee_hass/assets/79198927/95c559b8-908e-4196-a4ff-6393ab997d75)

The total energy easee sensor is also kWh

**Comment by jakobschou** [comment]
So it seems the easee sensor is just dating the kWh 1 hour late. See this example

Total
![image](https://github.com/nordicopen/easee_hass/assets/79198927/808f3ec4-26d4-4e00-ac6c-0ea8ef480ac8)

Easee
![image](https://github.com/nordicopen/easee_hass/assets/79198927/6e7d6e3b-e8d5-4efb-9cc9-ab08cebe6468)

**Comment by olalid** [comment]
As I said above there is no concept of "dating" in HA, the timestamp that is recorded is when the data is received/updated. There is no way to change that.
The input data is not really incorrect, it is just how HA interprets it in combination with when data is sent out from Easee that causes this.

The way HA interprets energy data is that records the difference between previous value and current value as being part of the current hour (well, there is a short grace period of I think 4.5 minutes after each hour where the first value received is considered to be part of the previous hour, but that is not really important in your case).

So lets say for instance that you get an update at 00:30:00 which says 1kWh. Then you get an update at 01:20:00 that says 2kWh. That difference (2-1 kWh = 1kWh) will be recorded as being part of the hour between 01:00 and 02:00, while in reality probably like half of it should belong to the previous hour. The algorithm in HA works fine if you have a sensor that updates often, but when you have these sensors that update more seldom like the lifetime_energy sensor in your case you get these kind of effects where data appear to be delayed.

So again, problem noted, but there is nothing we can do about it.

**Comment by olalid** [comment]
Data is pushed out, so we are not really in control of that.

**Comment by olalid** [comment]
I made a test to be sure, but seems even if I poll the lifetime energy data, I will only get the last pushed out value, until a new value is pushed out and I will get that instead. So really there is nothing to gain by polling (more frequently than values are pushed out). I will close this issue now since there is no obvious way to improve it.

**Comment by basdp** [comment]
There is not 'nothing' we can do. If the use case is you need the 'live' energy usage at any point in time (not the hourly updated usage that is updated after the hour mark, thus an hour late in your energy dashboard), you can use the Left Riemann sum ('Linker Riemann som' in Dutch) over the current usage (current power sensor) in a HA helper. That will give you what you need. 
Perhaps we can add this to the readme?
