### ISSUE TITLE
Controlling Equalizer surplus mode

### ISSUE THREAD

**Issue by Sigersen** [nordicopen/easee_hass#392]
### Feature request

I’m new to the whole HA universe, so I hope I’m making this request in a proper way.
I am creating some simple automations in HA, and keep missing the ability to turn surplus charging/solar mode on and off automatically. 
for example if it’s after sunset and the car is not done charging, the surplus mode will have to turn off.

is this even possible?

best regards
Anders from Denmark
![IMG_7922](https://github.com/nordicopen/easee_hass/assets/153859493/76e67861-3313-4284-b323-634dac55f1ee)

### What version of the integration are you using?

v0.9.57

**Comment by olalid** [comment]
Well that is an interesting question. I can not really find an API when I looked quickly.
I will investigate further...

**Comment by olalid** [comment]
So far I know that there is a "observation" in the signalr stream for this:
state_surplusCharging { "mode":1, "standbycurrent":0 }
Mode seems to mean 0 = off, 1 = on, and what the app calls "surplus only" is when standbycurrent = 0, and "limited grid usage" is when standbycurrent > 0.
So we could create a sensor for it, but there is no obvious way to control the setting that I am aware of.
Obviously there is since the app can do it, but it is not documented as far as I can see.

**Comment by Sigersen** [comment]
Okay! I really appreciate that you tried!
I’ll just cross my fingers that it will be possible in the future. Perhaps when surplus mode is no longer in a beta state. I believe the “normal charging at night” option should be a standard option in the Easee app actually. Lets see. Thank you for trying!

**Comment by olalid** [comment]
Yes, the API documentation is lagging a bit from what is actually implemented, as soon as we know more we can work on this.
