### ISSUE TITLE
multiple chargers; possibility to override circuit_dynamic_limit? (combine PV surplus charging and smart (low-cost) charging)

### ISSUE THREAD

**Issue by HolgerMiara** [nordicopen/easee_hass#417]
### Question

Hi, 
I have just installed my second Easee Home charger on the same circuit (25 Amp). In the past, I have successfully either charged with solar (surplus) power, or -- whenever that wasn't enough' -- I applied "smart" charging through the "[EV Smart Charging integration](https://github.com/jonasbkarlsson/ev_smart_charging/)". For both purposes, I controlled the charger via the `service: easee.set_circuit_dynamic_limit` as recommended. 

But now, with the second charger, I try to get my head around the following: 

- `service: easee.set_circuit_dynamic_limit` -- is perfect for telling a group of chargers how much solar power they are allowed to use. It is my hope that the chargers will prioritize among themselves and make sure that both cars are charged within the limits of available (surplus) power. 
- `service: easee.set_charger_dynamic_limit` -- this is probably the one which I have to use, if I want to control the chargers individually for smart charging. As suggested in this post of @enoch85: https://github.com/nordicopen/easee_hass/issues/256#issuecomment-1774129683. But it only works, if I resume the dynamic limit for all other chargers. Therefore, if I want to "boost" charging of a particular car, I need to resume the dynamic limit to full power for all chargers and thereafter limit charging of all chargers, which shall not be boosted / smart charged. 

My question was, whether there is a smarter way of doing this, a kind of switch or command that overrides the 'circuit_dynamic_limit' on a particular charger, while keeping it the same on all others on the same circuit. Like a "boost" function on one particular charger while not affecting the others. 

Are there any recommendations? Would a `easee.set_basic_charge_plan` maybe override the circuit dynamic limit?

### What version of the integration are you using?

0.9.58

**Comment by olalid** [comment]
Well, everything you can do is really putting different current limits on circuits or chargers in a sense.

The dynamic circuit limit affects all chargers on that circuit, i.e. if you set it to 12A and have 2 chargers on that circuit, each of the chargers can charge with 6A maximum at the same time, or one can charge with 12A if the other is not used of by other means is stopped from charging. If there is less than 12A available, only one charger will be able to start charging, how the priority between them works I am not sure, I do not have this kind of setup myself.

The dynamic charger limit affects only the specific charger, so if you set it to 5A or less it will stop that charger from starting. Note though that it will reset every time a car is plugged in to the charger, so you can not expect it to keep the value you set forever.

The charge plan has a similar affect, it limits the current to 0 on a charger when it is outside of the schedule. So that would work too.

**Comment by HolgerMiara** [comment]
Dear @olalid, thanks a lot for your reply!

You confirmed my considerations. Probably I will run a mix, with all chargers being controlled simultaneously by dynamic circuit limit for PV (surplus) charging. Am curious myself how they are going to prioritise among themselves, I haven't seen any options in the Easee app yet. 

And whenever I want to boost charging on a particular charger, I will restrict all other chargers on the same circuit with 0 Amp dynamic charger limit and reset the dynamic circuit limit to full power. 

Slightly counter-intuitive, but it should work =)

Thanks again and have a good day!

**Comment by HolgerMiara** [comment]
Never reported back, but it works just as @olalid described. 
If somebody is interested, this is how it has been running at my place over the past months. 

| Case              | Circuit dynamic limit | Charger-1 dynamic limit | Charger-2 dynamic limit | 
| :---------------- | ------: | ----: | ----: |
| default        |   **0**   | fuse rating, in my case 25 | fuse rating, in my case 25 |
| PV surplus charging |   **dynamic**  | 25 | 25 |
| Boost first charger   |  25  | **16** | 0 | 
| Boost second charger    |  25  | 0 | **16** | 
| Boost both chargers    |  25  | **16** | **16** |
