### ISSUE TITLE
Weekly plan charging current limit

### ISSUE THREAD

**Issue by KevinNL1999** [nordicopen/easee_hass#425]
### Feature request

According to the API endpoint specification of Set Weekly Charge Plan (https://developer.easee.com/reference/post_api-chargers-chargerid-weekly-charge-plan), there is a body parameter for chargingCurrentLimit. I am missing this parameter in the integration, I can only supply week day and start/stop time.

### What version of the integration are you using?

0.9.59

**Comment by olalid** [comment]
Hmm, I am pretty sure this must have been added to the API fairly recently since I do not remember that it was possible to set that when I looked at it last.
It seems to be true also for the basic charge plan:
https://developer.easee.com/reference/post_api-chargers-chargerid-basic-charge-plan

This is definitely something we should add.

**Comment by olalid** [comment]
pyeasee changes in this PR: https://github.com/nordicopen/pyeasee/pull/103/files
Needs changes in component too.

**Comment by olalid** [comment]
Work in progress still, but included here: https://github.com/nordicopen/easee_hass/pull/483

**Comment by olalid** [comment]
Released now, please let us know if your problem was solved.
