### ISSUE TITLE
Spikes in total energy consumption

### ISSUE THREAD

**Issue by erikfluff** [nordicopen/easee_hass#440]
### The problem

I have an equalizer connected to an Aidon meter. Almost every month i get one or two crazy spikes in my total consumption sensor, it seems like it moves the decimal one step for one or two hours, and then move back, so the total consumtion is 35 548,8 kwh at one hour, and then 355 549,2 kwh the next hour, and then back to 35 550,3 kwh, making the energy dashboard crazy. I don't know if it is my aidon meter or the equalizer that is acting up. Maybe its possible to create a filter for theese kinds of events?

![spik1](https://github.com/user-attachments/assets/e1ff4ac5-36a2-4940-9565-dea3c42637c3)
![spik2](https://github.com/user-attachments/assets/fb6e18fb-de1c-4e77-b0da-f3b77c05c64c)

### Version of Easee integration having the issue?

0.9.59

### Version of Home Assistant Core having the issue?

2024.6.3

**Comment by olalid** [comment]
If you turn on logging (see readme) and look for the keyword state_cumulativeActivePowerImport you can see the value that Easee reports back to the integrateion. This value is always in kWh.
If you can see the incorrect values to match what you see in HA UI then the problem really lies on Easee or meter side and I suggest you also report it to Easee if so.

I can see how it is annoying but I am kind of reluctant to make workarounds for issues that are in fact caused by bugs in other systems. Maybe you can use an outlier filter to fix this for your specific case?
https://www.home-assistant.io/integrations/filter/
