### ISSUE TITLE
Lifetime energy out of sync when used to track individual devices in Energy tab

### ISSUE THREAD

**Issue by djoenez** [nordicopen/easee_hass#462]
### The problem

I'm tracking the easee charger in the energy dashboard as an entity (lifetime energy). But what i now see is that the untracked consumption is up one hour, and the +1 hour you have the easee charger with a negative untracked consumption
![image](https://github.com/user-attachments/assets/b90eaf3f-0019-4eb1-94d7-99d007506749)

### Version of Easee integration having the issue?

0.9.59

### Version of Home Assistant Core having the issue?

2024.9.0

**Comment by olalid** [comment]
This has been discussed several times before, it is not possible to do anything to improve this since it is an inherant problem related to how data is reported from the cloud compared to how it would need to be delivered to HA to get the correct information. See for instance https://github.com/nordicopen/easee_hass/issues/387

**Comment by epaulsen** [comment]
I used to have the same issue with the energy dashboard, stumbled upon this while searching for something else.
My workaround is to use a Rienmann integral sum helper on the power sensor from the Easee integration, and force that one to update every minute.  Works like expected in both the energy dashboard and my price calculations.
![image](https://github.com/user-attachments/assets/877c0ebd-9a95-4d12-861d-f028f37c7224)
![image](https://github.com/user-attachments/assets/e2acd4f9-f6c3-43df-8008-8740d29cd356)
