### ISSUE TITLE
Websockets is outdated in new version of HA: easee not working anymore

### ISSUE THREAD

**Issue by MarkP12345** [nordicopen/easee_hass#505]
### Before creating an issue...

- [X] There is no open issue describing the same problem
- [X] I am running latest versions of the integration and of Home Assistant
- [X] I have checked the operational status of the Easee API

### The problem

The error ModuleNotFoundError: No module named 'websockets.legacy.exceptions' usually appears when a Python package is missing or outdated. This error is often related to the websockets library, which is a dependency in some frameworks or integrations, such as Home Assistant.

### Version of Easee integration having the issue?

latest

### Version of Home Assistant Core having the issue?

core

### Anything in the logs that might be useful for us?

```txt
The error ModuleNotFoundError: No module named 'websockets.legacy.exceptions' usually appears when a Python package is missing or outdated. This error is often related to the websockets library, which is a dependency in some frameworks or integrations, such as Home Assistant.
```

**Comment by olalid** [comment]
Seems to me that your installation is broken.

What version of websockets does your installation have? This integrations requires 12.x through the requirements of pysignalr 1.0.

**Comment by MarkP12345** [comment]
This error occured after installation of the most recent HA core (2024.11.1)

**Comment by olalid** [comment]
Again, this is a problem with your environment, not with this integration.

It appears like you have the incorrect version of websockets, or one of websockets requirements are not fulfilled correctly.
If you do a "ls /usr/local/lib/python3.12/site-packages/websockets*" you should see what version is installed, at least that is the path that is stated in the logs above.
For me this displays websockets-12.0.dist-info.
If you have 13.x something, it is incompatible and needs to be uninstalled.

webostv integration which is mentioned in your logs relies on aiowebostv which also requires websockets, but version >= 10.3, but I think that is probably not correct, it will probably not work with 13.x either because of incompatibilities introduced in 13.0.

**Comment by MarkP12345** [comment]
Sorry it appeared to be a problem with my NUC. Restarting proxmox did the trick. I will close this one. Thanks for your cooperation!

**Comment by MarkP12345** [comment]
Solved

**Comment by nexeck** [comment]
@MarkP12345 Just to mention this issue from home-assistant/core related to the websocket topic: https://github.com/home-assistant/core/issues/130725 & https://github.com/baking-bad/pysignalr/issues/23

**Comment by olalid** [comment]
We are aware. See https://github.com/nordicopen/pyeasee/issues/118
