### ISSUE TITLE
Trigger when car is connected

### ISSUE THREAD

**Issue by nibbles-** [nordicopen/easee_hass#509]
### Question

I am having a bit of a broken brain atm so I figured I should just ask.

I am setting up an automation that triggers on change of the electricity price (nordpool integration) an starting/stopping charging based on that price.
However I also want the automation to trigger when I connect the the car so I dont have to wait for the next price change to happen.

There is a State that I can trigger on when the car is disconnected. But what about the opposite?

### What version of the integration are you using?

0.9.64

**Comment by olalid** [comment]
All the different states (that we know about) can be seen here:

https://github.com/nordicopen/easee_hass/blob/a50459831160186c510bda7e69690b44272ddbb2/custom_components/easee/const.py#L938-L962

I think triggering an automation on state and from: "disconnected" is a valid way to see if the charger is changing from disconnected to whatever else? There is a slight chance the charger is in some kind of error state of course, but that probably does not matter since that is something that requires user intervention anyway.

A suggestion though is to run your automation once a minute instead of triggered on state changing alone, and use conditions in the automation to decide if charging should be started or stopped, or just set the circuit dynamic limit depending on some other predetermined template sensor. If you do that, you are not dependant on that the Easee API works every time, and a short outage will not cause any issue.

**Comment by nibbles-** [comment]
Many thanks. Will try that.

**Comment by nibbles-** [comment]
A followup with regards to triggering every minute.

Wont this spam the API with a request every minute? Or is the integration smart enough to only do something if the value changes?

**Comment by olalid** [comment]
Depends on what service you call.
All the services for setting current limits are smart and does not call the API if there if the settings has not changed.

**Comment by nibbles-** [comment]
So a timebased trigger works great. But I wanted to also have a more "event based" trigger so I looked into the "state change from disconnected".

But it doesnt look like its possible. I am using the GUI and if I use Device-based trigger I dont get the option to select the "State-change" only if its in the Disconnected state.
If I choose the Entitybased trigger I dont have the option to select those states.

Thoughts?

**Comment by nibbles-** [comment]
The problem is that the states are not selectable

![bild](https://github.com/user-attachments/assets/6060a35a-712e-4aa2-aa46-b72227451eb0)

**Comment by olalid** [comment]
Can you not type whatever in that field?

**Comment by nibbles-** [comment]
😬 Didn't even cross my mind to try.

Works like a charm.
Thanks

Den tors 14 nov. 2024 11:40Ola Lidholm ***@***.***> skrev:
