### ISSUE TITLE
Easee Home reverting to fallback current

### ISSUE THREAD

**Issue by trappify** [nordicopen/easee_hass#520]
### Before creating an issue...

- [X] There is no open issue describing the same problem
- [X] I am running latest versions of the integration and of Home Assistant
- [X] I have checked the operational status of the Easee API

### The problem

Hi guys,

My Easee home have started to charge using the fallback current setting, as in being offline. Could this somehow be related to the reported SignalR issues? I'm running HA 2024.11.1 with Easee integration v0.9.64 (which I think is the latest available).

I opened a case with Easee and they are telling me the following: 

_"We have investigated further and can see that the issue may lie in the connection between your charger and the load balancing system you are using. 
 
It seems that they are losing connection with one another, due to either the charger or the load balancing system going offline momentarily, and then not regaining full communication, reducing the efficacy of the charging and causing the charger to recognise an offline connection and revert to the offline fallback. "_

I didn't think the Easee integration would be considered a "load balancing system" from their end, but I'm starting to suspect I'm wrong there.

Any ideas on how to troubleshoot this further is very welcome.

### Version of Easee integration having the issue?

0.9.64

### Version of Home Assistant Core having the issue?

2024.11.1

### Additional information
 ![IMG_3367](https://github.com/user-attachments/assets/02489f09-11a7-49af-87af-7edd9819836d)
_No response_

**Comment by trappify** [comment]
My apologies if this should have been submitted as a support request. First time posting ... :(

**Comment by olalid** [comment]
Well, you did not mention if you do have a load balancing equipment installed?
I.e. something like Easee Equalizer, Tibber Pulse etc?

I doubt that the integration loosing connection over signalr could casue this kind of behaviour.
The issue we have had is not about loosing connection in any case, it is to establish it. Unless you have a rather flaky internet connection once the connection has been established it stays established. In any case, this was solved in v0.9.64.
You can look in your log files for "SR stream connected". Normally you would see that only once in the log file.

If we look at how the Easee equalizer works, it has several different ways to communicate with the charger. First there is a local RF interface over 433 or 868 MHz (not sure which) that sends information from the equalizer to the charger every time it receives data from the meter. Second, the equalizer broadcasts a packet of data (encrypted unfortunately) over WiFi with the same data. Third, it sends the data to the cloud. If any of these 3 paths is successfully conveying the data I think that would mean that it would be considered "online".

This integration does not have the ability to send data on any of those local paths, we get everything from the cloud.
The integration can of course act "like" a load balancer in the sense that it can control different charger current limits, but that is something you would have to write your own automations to accomplish, it is not something it does out of the box.

I would not think this integration could cause the above error, since it is not using the "correct" interface in to the charger and/or cloud to be considered a load balancer.

**Comment by trappify** [comment]
I have a Tibber Pulse installed and integrated with HA. I have an automation set up in HA to control the Easee charger via the easee.set_charger_dynamic_limit command. It will adjust the current based on the data I read from tibber pulse. However, there is no direct integration between the Pulse and Easee afaik (unless you let Tibber manage the charging process). The actual load balancing is done by the automation in HA. This was working fine for a couple of weeks, until yesterday when it started to cap the speed at the offline current setting. So I'm a bit puzzled that Easee is talking about "Load balancing" since I'm not aware of having such integration between Easee and Pulse :)

**Comment by trappify** [comment]
> Well, you did not mention if you do have a load balancing equipment installed? I.e. something like Easee Equalizer, Tibber Pulse etc?
> 
> I doubt that the integration loosing connection over signalr could casue this kind of behaviour. The issue we have had is not about loosing connection in any case, it is to establish it. Unless you have a rather flaky internet connection once the connection has been established it stays established. In any case, this was solved in v0.9.64. You can look in your log files for "SR stream connected". Normally you would see that only once in the log file.
> 
> If we look at how the Easee equalizer works, it has several different ways to communicate with the charger. First there is a local RF interface over 433 or 868 MHz (not sure which) that sends information from the equalizer to the charger every time it receives data from the meter. Second, the equalizer broadcasts a packet of data (encrypted unfortunately) over WiFi with the same data. Third, it sends the data to the cloud. If any of these 3 paths is successfully conveying the data I think that would mean that it would be considered "online".
> 
> This integration does not have the ability to send data on any of those local paths, we get everything from the cloud. The integration can of course act "like" a load balancer in the sense that it can control different charger current limits, but that is something you would have to write your own automations to accomplish, it is not something it does out of the box.
> 
> I would not think this integration could cause the above error, since it is not using the "correct" interface in to the charger and/or cloud to be considered a load balancer.



> I have a Tibber Pulse installed and integrated with HA. I have an automation set up in HA to control the Easee charger via the easee.set_charger_dynamic_limit command. It will adjust the current based on the data I read from tibber pulse. However, there is no direct integration between the Pulse and Easee afaik (unless you let Tibber manage the charging process). The actual load balancing is done by the automation in HA. This was working fine for a couple of weeks, until yesterday when it started to cap the speed at the offline current setting. So I'm a bit puzzled that Easee is talking about "Load balancing" since I'm not aware of having such integration between Easee and Pulse (other than my automation in HA).

I have a Tibber Pulse installed and integrated with HA. I have an automation set up in HA to control the Easee charger via the easee.set_charger_dynamic_limit command. It will adjust the current based on the data I read from tibber pulse. However, there is no direct integration between the Pulse and Easee afaik (unless you let Tibber manage the charging process). The actual load balancing is done by the automation in HA. This was working fine for a couple of weeks, until yesterday when it started to cap the speed at the offline current setting. So I'm a bit puzzled that Easee is talking about "Load balancing" since I'm not aware of having such integration between Easee and Pulse (other than my automation in HA).

**Comment by olalid** [comment]
It could be so that Tibber pulse is able to send out these broadcast packets over WiFi that can be interpreted by Easee charger.
I have never used a Tibber pulse myself so I have no experience of how it works.

If you look in your Easee app, do you see a separate row that indicates that it sees some kind of load balancer (in the same view as your screenshot above, but further down)? In my app there is a row that states "Equalizer limit 17/17/16 A". There is also a sensor in the integration called "equalizer_limit" which has attributes for the separate phases.

**Comment by olalid** [comment]
Yes, you can control the limits with automations in HA regardless of any load balancer.

Have you tried using dynamic circuit limit instead of dynamic charger limit?
First, it is better because it is remembered between charging sessions (meaning that charging will not start even if you plug in and it is set to less than 6A), second you can if you want set a time limit on it, so that it is discarded if you loose connection with HA after that time.
If you have more than one charger and want to control which one is started, then of course this may be limiting if they are on the same circuit.

Other than that, I would look in to if any of your devices actually go offline now and then, charger, HA, pulse. If so that may be the explanation.

**Comment by trappify** [comment]
> Yes, you can control the limits with automations in HA regardless of any load balancer.
> 
> Have you tried using dynamic circuit limit instead of dynamic charger limit? First, it is better because it is remembered between charging sessions (meaning that charging will not start even if you plug in and it is set to less than 6A), second you can if you want set a time limit on it, so that it is discarded if you loose connection with HA after that time. If you have more than one charger and want to control which one is started, then of course this may be limiting if they are on the same circuit.
> 
> Other than that, I would look in to if any of your devices actually go offline now and then, charger, HA, pulse. If so that may be the explanation.

Thanks for confirming. I've not tried using dynamic circuit limit, but will definitely try it now!

I was using Tibber to manage my charging previously, which has been working great. However my car (ID4) draws power from the charger during preconditioning, which often coincides with the morning peak hours. Tibber tells me they can't do anything about it. Car specific. But with HA and the Easee integration, I can make sure to disable the charger at 06 in the morning, which then forces the car to just precondition from the battery.

Now it crossed my mind that maybe it's possible to let Tibber manage the charging and just disable the charger from HA when I want to prevent it from charging, e.g. between 06-09.  Not sure if Easee will accept that when Tibber is the selected operator. I'll play around with the dynamic circuit limit call and see if that does the trick. Otherwise I could try going back to Tibber.

Thanks a lot for the support! This is likely not a bug in the Easee integration then. So perhaps just close this out.

**Comment by olalid** [comment]
Whichever limit is the lowest will be the limit that controls the charger, should not matter if Tibber is controlling the charger or not, as long as it and you are not trying to control the same limit.

**Comment by trappify** [comment]
Just wrapping this up in case it can help someone else. I ended up moving back to Tibber as the primary controller for the charger, but kept the HA Easee integration. Now I just have an automation that disables the charger at 06:00 and enables it again at 22:00. That way it can't draw any current during the peak hours, which was my ultimate goal. Have been running like this for a few days now and seems to work well.

Thanks a lot for your support.
